# Dockerfile

FROM openjdk:11
MAINTAINER Author Name <soumyabk2810@gmail.com>

WORKDIR /app


COPY /target/WorkerJavaApplication-0.0.1-SNAPSHOT-jar-with-dependencies.jar ./
 
CMD [ "java -jar WorkerJavaApplication-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]